/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/state-tunnel';
import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppHome {
    'myFunc': () => void;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'myFunc'?: () => void;
  }

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface MyTunnelConsumer {}
  interface MyTunnelConsumerAttributes extends StencilHTMLAttributes {}

  interface MyTunnelProvider {
    'message': string;
  }
  interface MyTunnelProviderAttributes extends StencilHTMLAttributes {
    'message'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'MyTunnelConsumer': Components.MyTunnelConsumer;
    'MyTunnelProvider': Components.MyTunnelProvider;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'my-tunnel-consumer': Components.MyTunnelConsumerAttributes;
    'my-tunnel-provider': Components.MyTunnelProviderAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLMyTunnelConsumerElement extends Components.MyTunnelConsumer, HTMLStencilElement {}
  var HTMLMyTunnelConsumerElement: {
    prototype: HTMLMyTunnelConsumerElement;
    new (): HTMLMyTunnelConsumerElement;
  };

  interface HTMLMyTunnelProviderElement extends Components.MyTunnelProvider, HTMLStencilElement {}
  var HTMLMyTunnelProviderElement: {
    prototype: HTMLMyTunnelProviderElement;
    new (): HTMLMyTunnelProviderElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'my-tunnel-consumer': HTMLMyTunnelConsumerElement
    'my-tunnel-provider': HTMLMyTunnelProviderElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'my-tunnel-consumer': HTMLMyTunnelConsumerElement;
    'my-tunnel-provider': HTMLMyTunnelProviderElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
